#-------------------------------------------------
#
# Project created by QtCreator 2023-06-07T21:40:15
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = Qt_lvgl_sim
TEMPLATE = app

INCLUDEPATH += $$PWD/../../Drivers/lvgl/

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS QT_EDITOR LV_LVGL_H_INCLUDE_SIMPLE

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0


SOURCES += main.cpp\
        mainwindow.cpp \
    ../../Drivers/lvgl/core/lv_disp.c \
    ../../Drivers/lvgl/core/lv_event.c \
    ../../Drivers/lvgl/core/lv_group.c \
    ../../Drivers/lvgl/core/lv_indev.c \
    ../../Drivers/lvgl/core/lv_indev_scroll.c \
    ../../Drivers/lvgl/core/lv_obj.c \
    ../../Drivers/lvgl/core/lv_obj_class.c \
    ../../Drivers/lvgl/core/lv_obj_draw.c \
    ../../Drivers/lvgl/core/lv_obj_pos.c \
    ../../Drivers/lvgl/core/lv_obj_scroll.c \
    ../../Drivers/lvgl/core/lv_obj_style.c \
    ../../Drivers/lvgl/core/lv_obj_style_gen.c \
    ../../Drivers/lvgl/core/lv_obj_tree.c \
    ../../Drivers/lvgl/core/lv_refr.c \
    ../../Drivers/lvgl/core/lv_theme.c \
    ../../Drivers/lvgl/draw/arm2d/lv_gpu_arm2d.c \
    ../../Drivers/lvgl/draw/nxp/pxp/lv_draw_pxp.c \
    ../../Drivers/lvgl/draw/nxp/pxp/lv_draw_pxp_blend.c \
    ../../Drivers/lvgl/draw/nxp/pxp/lv_gpu_nxp_pxp.c \
    ../../Drivers/lvgl/draw/nxp/pxp/lv_gpu_nxp_pxp_osa.c \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite.c \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite_arc.c \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite_blend.c \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite_line.c \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite_rect.c \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_vglite_buf.c \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_vglite_utils.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_arc.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_bg.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_composite.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_img.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_label.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_layer.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_line.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_mask.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_polygon.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_rect.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_stack_blur.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_texture_cache.c \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_utils.c \
    ../../Drivers/lvgl/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_arc.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_blend.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_dither.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_gradient.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_img.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_layer.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_letter.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_line.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_polygon.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_rect.c \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_transform.c \
    ../../Drivers/lvgl/draw/swm341_dma2d/lv_gpu_swm341_dma2d.c \
    ../../Drivers/lvgl/draw/lv_draw.c \
    ../../Drivers/lvgl/draw/lv_draw_arc.c \
    ../../Drivers/lvgl/draw/lv_draw_img.c \
    ../../Drivers/lvgl/draw/lv_draw_label.c \
    ../../Drivers/lvgl/draw/lv_draw_layer.c \
    ../../Drivers/lvgl/draw/lv_draw_line.c \
    ../../Drivers/lvgl/draw/lv_draw_mask.c \
    ../../Drivers/lvgl/draw/lv_draw_rect.c \
    ../../Drivers/lvgl/draw/lv_draw_transform.c \
    ../../Drivers/lvgl/draw/lv_draw_triangle.c \
    ../../Drivers/lvgl/draw/lv_img_buf.c \
    ../../Drivers/lvgl/draw/lv_img_cache.c \
    ../../Drivers/lvgl/draw/lv_img_decoder.c \
    ../../Drivers/lvgl/extra/layouts/flex/lv_flex.c \
    ../../Drivers/lvgl/extra/layouts/grid/lv_grid.c \
    ../../Drivers/lvgl/extra/libs/bmp/lv_bmp.c \
    ../../Drivers/lvgl/extra/libs/ffmpeg/lv_ffmpeg.c \
    ../../Drivers/lvgl/extra/libs/freetype/lv_freetype.c \
    ../../Drivers/lvgl/extra/libs/fsdrv/lv_fs_fatfs.c \
    ../../Drivers/lvgl/extra/libs/fsdrv/lv_fs_posix.c \
    ../../Drivers/lvgl/extra/libs/fsdrv/lv_fs_stdio.c \
    ../../Drivers/lvgl/extra/libs/fsdrv/lv_fs_win32.c \
    ../../Drivers/lvgl/extra/libs/gif/gifdec.c \
    ../../Drivers/lvgl/extra/libs/gif/lv_gif.c \
    ../../Drivers/lvgl/extra/libs/png/lodepng.c \
    ../../Drivers/lvgl/extra/libs/png/lv_png.c \
    ../../Drivers/lvgl/extra/libs/qrcode/lv_qrcode.c \
    ../../Drivers/lvgl/extra/libs/qrcode/qrcodegen.c \
    ../../Drivers/lvgl/extra/libs/rlottie/lv_rlottie.c \
    ../../Drivers/lvgl/extra/libs/sjpg/lv_sjpg.c \
    ../../Drivers/lvgl/extra/libs/sjpg/tjpgd.c \
    ../../Drivers/lvgl/extra/others/fragment/lv_fragment.c \
    ../../Drivers/lvgl/extra/others/fragment/lv_fragment_manager.c \
    ../../Drivers/lvgl/extra/others/gridnav/lv_gridnav.c \
    ../../Drivers/lvgl/extra/others/ime/lv_ime_pinyin.c \
    ../../Drivers/lvgl/extra/others/imgfont/lv_imgfont.c \
    ../../Drivers/lvgl/extra/others/monkey/lv_monkey.c \
    ../../Drivers/lvgl/extra/others/msg/lv_msg.c \
    ../../Drivers/lvgl/extra/others/snapshot/lv_snapshot.c \
    ../../Drivers/lvgl/extra/themes/basic/lv_theme_basic.c \
    ../../Drivers/lvgl/extra/themes/default/lv_theme_default.c \
    ../../Drivers/lvgl/extra/themes/mono/lv_theme_mono.c \
    ../../Drivers/lvgl/extra/widgets/animimg/lv_animimg.c \
    ../../Drivers/lvgl/extra/widgets/calendar/lv_calendar.c \
    ../../Drivers/lvgl/extra/widgets/calendar/lv_calendar_header_arrow.c \
    ../../Drivers/lvgl/extra/widgets/calendar/lv_calendar_header_dropdown.c \
    ../../Drivers/lvgl/extra/widgets/chart/lv_chart.c \
    ../../Drivers/lvgl/extra/widgets/colorwheel/lv_colorwheel.c \
    ../../Drivers/lvgl/extra/widgets/imgbtn/lv_imgbtn.c \
    ../../Drivers/lvgl/extra/widgets/keyboard/lv_keyboard.c \
    ../../Drivers/lvgl/extra/widgets/led/lv_led.c \
    ../../Drivers/lvgl/extra/widgets/list/lv_list.c \
    ../../Drivers/lvgl/extra/widgets/menu/lv_menu.c \
    ../../Drivers/lvgl/extra/widgets/meter/lv_meter.c \
    ../../Drivers/lvgl/extra/widgets/msgbox/lv_msgbox.c \
    ../../Drivers/lvgl/extra/widgets/span/lv_span.c \
    ../../Drivers/lvgl/extra/widgets/spinbox/lv_spinbox.c \
    ../../Drivers/lvgl/extra/widgets/spinner/lv_spinner.c \
    ../../Drivers/lvgl/extra/widgets/tabview/lv_tabview.c \
    ../../Drivers/lvgl/extra/widgets/tileview/lv_tileview.c \
    ../../Drivers/lvgl/extra/widgets/win/lv_win.c \
    ../../Drivers/lvgl/extra/lv_extra.c \
    ../../Drivers/lvgl/font/lv_font.c \
    ../../Drivers/lvgl/font/lv_font_dejavu_16_persian_hebrew.c \
    ../../Drivers/lvgl/font/lv_font_fmt_txt.c \
    ../../Drivers/lvgl/font/lv_font_loader.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_10.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_12.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_12_subpx.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_14.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_16.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_18.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_20.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_22.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_24.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_26.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_28.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_28_compressed.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_30.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_32.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_34.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_36.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_38.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_40.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_42.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_44.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_46.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_48.c \
    ../../Drivers/lvgl/font/lv_font_montserrat_8.c \
    ../../Drivers/lvgl/font/lv_font_simsun_16_cjk.c \
    ../../Drivers/lvgl/font/lv_font_unscii_16.c \
    ../../Drivers/lvgl/font/lv_font_unscii_8.c \
    ../../Drivers/lvgl/hal/lv_hal_disp.c \
    ../../Drivers/lvgl/hal/lv_hal_indev.c \
    ../../Drivers/lvgl/hal/lv_hal_tick.c \
    ../../Drivers/lvgl/misc/lv_anim.c \
    ../../Drivers/lvgl/misc/lv_anim_timeline.c \
    ../../Drivers/lvgl/misc/lv_area.c \
    ../../Drivers/lvgl/misc/lv_async.c \
    ../../Drivers/lvgl/misc/lv_bidi.c \
    ../../Drivers/lvgl/misc/lv_color.c \
    ../../Drivers/lvgl/misc/lv_fs.c \
    ../../Drivers/lvgl/misc/lv_gc.c \
    ../../Drivers/lvgl/misc/lv_ll.c \
    ../../Drivers/lvgl/misc/lv_log.c \
    ../../Drivers/lvgl/misc/lv_lru.c \
    ../../Drivers/lvgl/misc/lv_math.c \
    ../../Drivers/lvgl/misc/lv_mem.c \
    ../../Drivers/lvgl/misc/lv_printf.c \
    ../../Drivers/lvgl/misc/lv_style.c \
    ../../Drivers/lvgl/misc/lv_style_gen.c \
    ../../Drivers/lvgl/misc/lv_templ.c \
    ../../Drivers/lvgl/misc/lv_timer.c \
    ../../Drivers/lvgl/misc/lv_tlsf.c \
    ../../Drivers/lvgl/misc/lv_txt.c \
    ../../Drivers/lvgl/misc/lv_txt_ap.c \
    ../../Drivers/lvgl/misc/lv_utils.c \
    ../../Drivers/lvgl/widgets/lv_arc.c \
    ../../Drivers/lvgl/widgets/lv_bar.c \
    ../../Drivers/lvgl/widgets/lv_btn.c \
    ../../Drivers/lvgl/widgets/lv_btnmatrix.c \
    ../../Drivers/lvgl/widgets/lv_canvas.c \
    ../../Drivers/lvgl/widgets/lv_checkbox.c \
    ../../Drivers/lvgl/widgets/lv_dropdown.c \
    ../../Drivers/lvgl/widgets/lv_img.c \
    ../../Drivers/lvgl/widgets/lv_label.c \
    ../../Drivers/lvgl/widgets/lv_line.c \
    ../../Drivers/lvgl/widgets/lv_objx_templ.c \
    ../../Drivers/lvgl/widgets/lv_roller.c \
    ../../Drivers/lvgl/widgets/lv_slider.c \
    ../../Drivers/lvgl/widgets/lv_switch.c \
    ../../Drivers/lvgl/widgets/lv_table.c \
    ../../Drivers/lvgl/widgets/lv_textarea.c


HEADERS  += mainwindow.h \
    ../../Drivers/lvgl/core/lv_disp.h \
    ../../Drivers/lvgl/core/lv_event.h \
    ../../Drivers/lvgl/core/lv_group.h \
    ../../Drivers/lvgl/core/lv_indev.h \
    ../../Drivers/lvgl/core/lv_indev_scroll.h \
    ../../Drivers/lvgl/core/lv_obj.h \
    ../../Drivers/lvgl/core/lv_obj_class.h \
    ../../Drivers/lvgl/core/lv_obj_draw.h \
    ../../Drivers/lvgl/core/lv_obj_pos.h \
    ../../Drivers/lvgl/core/lv_obj_scroll.h \
    ../../Drivers/lvgl/core/lv_obj_style.h \
    ../../Drivers/lvgl/core/lv_obj_style_gen.h \
    ../../Drivers/lvgl/core/lv_obj_tree.h \
    ../../Drivers/lvgl/core/lv_refr.h \
    ../../Drivers/lvgl/core/lv_theme.h \
    ../../Drivers/lvgl/draw/arm2d/lv_gpu_arm2d.h \
    ../../Drivers/lvgl/draw/nxp/pxp/lv_draw_pxp.h \
    ../../Drivers/lvgl/draw/nxp/pxp/lv_draw_pxp_blend.h \
    ../../Drivers/lvgl/draw/nxp/pxp/lv_gpu_nxp_pxp.h \
    ../../Drivers/lvgl/draw/nxp/pxp/lv_gpu_nxp_pxp_osa.h \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite.h \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite_arc.h \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite_blend.h \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite_line.h \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_draw_vglite_rect.h \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_vglite_buf.h \
    ../../Drivers/lvgl/draw/nxp/vglite/lv_vglite_utils.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_composite.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_img.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_layer.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_mask.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_priv.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_rect.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_stack_blur.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_texture_cache.h \
    ../../Drivers/lvgl/draw/sdl/lv_draw_sdl_utils.h \
    ../../Drivers/lvgl/draw/stm32_dma2d/lv_gpu_stm32_dma2d.h \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw.h \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_blend.h \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_dither.h \
    ../../Drivers/lvgl/draw/sw/lv_draw_sw_gradient.h \
    ../../Drivers/lvgl/draw/swm341_dma2d/lv_gpu_swm341_dma2d.h \
    ../../Drivers/lvgl/draw/lv_draw.h \
    ../../Drivers/lvgl/draw/lv_draw_arc.h \
    ../../Drivers/lvgl/draw/lv_draw_img.h \
    ../../Drivers/lvgl/draw/lv_draw_label.h \
    ../../Drivers/lvgl/draw/lv_draw_layer.h \
    ../../Drivers/lvgl/draw/lv_draw_line.h \
    ../../Drivers/lvgl/draw/lv_draw_mask.h \
    ../../Drivers/lvgl/draw/lv_draw_rect.h \
    ../../Drivers/lvgl/draw/lv_draw_transform.h \
    ../../Drivers/lvgl/draw/lv_draw_triangle.h \
    ../../Drivers/lvgl/draw/lv_img_buf.h \
    ../../Drivers/lvgl/draw/lv_img_cache.h \
    ../../Drivers/lvgl/draw/lv_img_decoder.h \
    ../../Drivers/lvgl/extra/layouts/flex/lv_flex.h \
    ../../Drivers/lvgl/extra/layouts/grid/lv_grid.h \
    ../../Drivers/lvgl/extra/layouts/lv_layouts.h \
    ../../Drivers/lvgl/extra/libs/bmp/lv_bmp.h \
    ../../Drivers/lvgl/extra/libs/ffmpeg/lv_ffmpeg.h \
    ../../Drivers/lvgl/extra/libs/freetype/lv_freetype.h \
    ../../Drivers/lvgl/extra/libs/fsdrv/lv_fsdrv.h \
    ../../Drivers/lvgl/extra/libs/gif/gifdec.h \
    ../../Drivers/lvgl/extra/libs/gif/lv_gif.h \
    ../../Drivers/lvgl/extra/libs/png/lodepng.h \
    ../../Drivers/lvgl/extra/libs/png/lv_png.h \
    ../../Drivers/lvgl/extra/libs/qrcode/lv_qrcode.h \
    ../../Drivers/lvgl/extra/libs/qrcode/qrcodegen.h \
    ../../Drivers/lvgl/extra/libs/rlottie/lv_rlottie.h \
    ../../Drivers/lvgl/extra/libs/sjpg/lv_sjpg.h \
    ../../Drivers/lvgl/extra/libs/sjpg/tjpgd.h \
    ../../Drivers/lvgl/extra/libs/sjpg/tjpgdcnf.h \
    ../../Drivers/lvgl/extra/libs/lv_libs.h \
    ../../Drivers/lvgl/extra/others/fragment/lv_fragment.h \
    ../../Drivers/lvgl/extra/others/gridnav/lv_gridnav.h \
    ../../Drivers/lvgl/extra/others/ime/lv_ime_pinyin.h \
    ../../Drivers/lvgl/extra/others/imgfont/lv_imgfont.h \
    ../../Drivers/lvgl/extra/others/monkey/lv_monkey.h \
    ../../Drivers/lvgl/extra/others/msg/lv_msg.h \
    ../../Drivers/lvgl/extra/others/snapshot/lv_snapshot.h \
    ../../Drivers/lvgl/extra/others/lv_others.h \
    ../../Drivers/lvgl/extra/themes/basic/lv_theme_basic.h \
    ../../Drivers/lvgl/extra/themes/default/lv_theme_default.h \
    ../../Drivers/lvgl/extra/themes/mono/lv_theme_mono.h \
    ../../Drivers/lvgl/extra/themes/lv_themes.h \
    ../../Drivers/lvgl/extra/widgets/animimg/lv_animimg.h \
    ../../Drivers/lvgl/extra/widgets/calendar/lv_calendar.h \
    ../../Drivers/lvgl/extra/widgets/calendar/lv_calendar_header_arrow.h \
    ../../Drivers/lvgl/extra/widgets/calendar/lv_calendar_header_dropdown.h \
    ../../Drivers/lvgl/extra/widgets/chart/lv_chart.h \
    ../../Drivers/lvgl/extra/widgets/colorwheel/lv_colorwheel.h \
    ../../Drivers/lvgl/extra/widgets/imgbtn/lv_imgbtn.h \
    ../../Drivers/lvgl/extra/widgets/keyboard/lv_keyboard.h \
    ../../Drivers/lvgl/extra/widgets/led/lv_led.h \
    ../../Drivers/lvgl/extra/widgets/list/lv_list.h \
    ../../Drivers/lvgl/extra/widgets/menu/lv_menu.h \
    ../../Drivers/lvgl/extra/widgets/meter/lv_meter.h \
    ../../Drivers/lvgl/extra/widgets/msgbox/lv_msgbox.h \
    ../../Drivers/lvgl/extra/widgets/span/lv_span.h \
    ../../Drivers/lvgl/extra/widgets/spinbox/lv_spinbox.h \
    ../../Drivers/lvgl/extra/widgets/spinner/lv_spinner.h \
    ../../Drivers/lvgl/extra/widgets/tabview/lv_tabview.h \
    ../../Drivers/lvgl/extra/widgets/tileview/lv_tileview.h \
    ../../Drivers/lvgl/extra/widgets/win/lv_win.h \
    ../../Drivers/lvgl/extra/widgets/lv_widgets.h \
    ../../Drivers/lvgl/extra/lv_extra.h \
    ../../Drivers/lvgl/font/lv_font.h \
    ../../Drivers/lvgl/font/lv_font_fmt_txt.h \
    ../../Drivers/lvgl/font/lv_font_loader.h \
    ../../Drivers/lvgl/font/lv_symbol_def.h \
    ../../Drivers/lvgl/hal/lv_hal.h \
    ../../Drivers/lvgl/hal/lv_hal_disp.h \
    ../../Drivers/lvgl/hal/lv_hal_indev.h \
    ../../Drivers/lvgl/hal/lv_hal_tick.h \
    ../../Drivers/lvgl/misc/lv_anim.h \
    ../../Drivers/lvgl/misc/lv_anim_timeline.h \
    ../../Drivers/lvgl/misc/lv_area.h \
    ../../Drivers/lvgl/misc/lv_assert.h \
    ../../Drivers/lvgl/misc/lv_async.h \
    ../../Drivers/lvgl/misc/lv_bidi.h \
    ../../Drivers/lvgl/misc/lv_color.h \
    ../../Drivers/lvgl/misc/lv_fs.h \
    ../../Drivers/lvgl/misc/lv_gc.h \
    ../../Drivers/lvgl/misc/lv_ll.h \
    ../../Drivers/lvgl/misc/lv_log.h \
    ../../Drivers/lvgl/misc/lv_lru.h \
    ../../Drivers/lvgl/misc/lv_math.h \
    ../../Drivers/lvgl/misc/lv_mem.h \
    ../../Drivers/lvgl/misc/lv_printf.h \
    ../../Drivers/lvgl/misc/lv_style.h \
    ../../Drivers/lvgl/misc/lv_style_gen.h \
    ../../Drivers/lvgl/misc/lv_templ.h \
    ../../Drivers/lvgl/misc/lv_timer.h \
    ../../Drivers/lvgl/misc/lv_tlsf.h \
    ../../Drivers/lvgl/misc/lv_txt.h \
    ../../Drivers/lvgl/misc/lv_txt_ap.h \
    ../../Drivers/lvgl/misc/lv_types.h \
    ../../Drivers/lvgl/misc/lv_utils.h \
    ../../Drivers/lvgl/widgets/lv_arc.h \
    ../../Drivers/lvgl/widgets/lv_bar.h \
    ../../Drivers/lvgl/widgets/lv_btn.h \
    ../../Drivers/lvgl/widgets/lv_btnmatrix.h \
    ../../Drivers/lvgl/widgets/lv_canvas.h \
    ../../Drivers/lvgl/widgets/lv_checkbox.h \
    ../../Drivers/lvgl/widgets/lv_dropdown.h \
    ../../Drivers/lvgl/widgets/lv_img.h \
    ../../Drivers/lvgl/widgets/lv_label.h \
    ../../Drivers/lvgl/widgets/lv_line.h \
    ../../Drivers/lvgl/widgets/lv_objx_templ.h \
    ../../Drivers/lvgl/widgets/lv_roller.h \
    ../../Drivers/lvgl/widgets/lv_slider.h \
    ../../Drivers/lvgl/widgets/lv_switch.h \
    ../../Drivers/lvgl/widgets/lv_table.h \
    ../../Drivers/lvgl/widgets/lv_textarea.h \
    ../../Drivers/lvgl/lv_api_map.h \
    ../../Drivers/lvgl/lv_conf.h \
    ../../Drivers/lvgl/lv_conf_internal.h \
    ../../Drivers/lvgl/lv_conf_kconfig.h \
    ../../Drivers/lvgl/lvgl.h


FORMS    += mainwindow.ui
